function esc(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function fmtDate(d) {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-UG', { day: 'numeric', month: 'long', year: 'numeric' });
}

/**
 * Builds a printable HTML letter of completion for an internship placement.
 */
function buildCompletionLetterHtml(data) {
  const ref = `IUG/COMP/${data.placementId}/${new Date().getFullYear()}`;
  const issued = fmtDate(data.completedAt || new Date());

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Letter of Completion — ${esc(data.studentName)}</title>
  <style>
    *{box-sizing:border-box;margin:0;padding:0;}
    body{font-family:'Segoe UI',Arial,sans-serif;color:#0f172a;background:#f1f5f9;padding:40px 20px;}
    .page{max-width:720px;margin:0 auto;background:#fff;border:1px solid #e2e8f0;border-radius:8px;padding:48px 56px;box-shadow:0 4px 24px rgba(15,23,42,.06);}
    .header{border-bottom:3px solid #d97706;padding-bottom:20px;margin-bottom:32px;}
    .brand{font-size:22px;font-weight:700;color:#0f172a;}
    .brand-sub{font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:#64748b;margin-top:4px;}
    .ref{font-size:12px;color:#64748b;margin-top:12px;}
    h1{font-size:20px;color:#0f172a;margin-bottom:24px;text-align:center;text-transform:uppercase;letter-spacing:.06em;}
    p{font-size:14px;line-height:1.75;margin-bottom:16px;color:#334155;}
    .highlight{font-weight:700;color:#0f172a;}
    .details{margin:24px 0;padding:20px 24px;background:#f8fafc;border-radius:8px;border-left:4px solid #d97706;}
    .details dt{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#64748b;margin-top:12px;}
    .details dt:first-child{margin-top:0;}
    .details dd{font-size:14px;font-weight:600;color:#0f172a;margin-top:2px;}
    .signatures{margin-top:48px;display:grid;grid-template-columns:1fr 1fr;gap:40px;}
    .sig-line{border-top:1px solid #0f172a;padding-top:8px;font-size:12px;color:#334155;}
    .footer{margin-top:40px;padding-top:20px;border-top:1px solid #e2e8f0;font-size:11px;color:#64748b;text-align:center;}
    @media print{
      body{background:#fff;padding:0;}
      .page{box-shadow:none;border:none;border-radius:0;padding:40px;}
      .no-print{display:none;}
    }
  </style>
</head>
<body>
  <div class="page">
    <div class="header">
      <div class="brand">InternUG</div>
      <div class="brand-sub">Uganda Internship Placement Portal</div>
      <div class="ref">Reference: ${esc(ref)} &nbsp;·&nbsp; Issued: ${esc(issued)}</div>
    </div>

    <h1>Letter of Completion</h1>

    <p>To whom it may concern,</p>

    <p>
      This is to certify that <span class="highlight">${esc(data.studentName)}</span>
      ${data.institution ? `of <span class="highlight">${esc(data.institution)}</span>` : ''}
      has successfully completed an internship placement with
      <span class="highlight">${esc(data.companyName)}</span>
      in the position of <span class="highlight">${esc(data.internshipTitle)}</span>.
    </p>

    <dl class="details">
      <dt>Internship period</dt>
      <dd>${esc(fmtDate(data.startDate))} — ${esc(fmtDate(data.endDate))}</dd>
      <dt>Total approved hours logged</dt>
      <dd>${esc(String(data.totalApprovedHours ?? 0))} hours</dd>
      <dt>Logbook entries on record</dt>
      <dd>${esc(String(data.logbookEntryCount ?? 0))} entries</dd>
      <dt>Placement status</dt>
      <dd>Completed</dd>
    </dl>

    <p>
      During this internship, the student maintained a digital logbook on InternUG,
      with daily work records available for future reference and clarification.
      This letter confirms satisfactory completion of the placement programme.
    </p>

    <div class="signatures">
      <div>
        <div class="sig-line">Authorised by: ${esc(data.companyName)}</div>
      </div>
      <div>
        <div class="sig-line">InternUG Platform — Official Record</div>
      </div>
    </div>

    <div class="footer">
      This document was generated by InternUG. Verify at internug.ug · ${esc(ref)}
    </div>
  </div>
  <p class="no-print" style="text-align:center;margin-top:20px;">
    <button onclick="window.print()" style="padding:12px 24px;background:#1e293b;color:#fff;border:none;border-radius:8px;font-size:14px;font-weight:600;cursor:pointer;box-shadow:0 3px 12px rgba(30,41,59,.25);">Print / Save as PDF</button>
  </p>
</body>
</html>`;
}

module.exports = { buildCompletionLetterHtml };
